(function(){
  const form=document.getElementById('signal-board-form');
  const status=document.getElementById('signal-form-status');
  const feed=document.getElementById('signal-board-feed');
  const accessButton=document.getElementById('unlock-signal-pass');
  const accessStatus=document.getElementById('forum-member-status')||document.querySelector('[data-signal-pass-status]')||document.getElementById('signal-pass-status');
  const submitSection=document.getElementById('submit-signal');

  const BOARD_LABELS={main:'Main Signal Board',speculation:'Dark Speculation Board','epstein-alive':'Epstein Alive / Sighting Board'};
  const FEED_ROUTES={main:'/forum-feed-main',speculation:'/forum-feed-speculation','epstein-alive':'/forum-feed-epstein-alive'};
  const SUBMIT_ROUTES={main:'/submit-main-post',speculation:'/submit-speculation-post','epstein-alive':'/submit-epstein-alive-post'};
  const REPORT_ROUTES={main:'/report-main-post',speculation:'/report-speculation-post','epstein-alive':'/report-epstein-alive-post'};
  const state={authenticated:false,member:null,checking:true};

  function boardFromPath(){const value=String(location.pathname||'').toLowerCase();if(value.includes('dark-speculation')||value.includes('speculation-board'))return'speculation';if(value.includes('epstein-alive')||value.includes('epstein-sighting'))return'epstein-alive';return'main'}
  function cleanBoard(value){const raw=String(value||'').replace(/[^a-z0-9-]/gi,'').toLowerCase();if(['speculation','darkspeculation','dark-speculation'].includes(raw))return'speculation';if(['epsteinalive','epstein-alive','epsteinsighting','epstein-sighting'].includes(raw))return'epstein-alive';if(raw==='main')return'main';return''}
  const boardRoot=document.querySelector('[data-board]')||document.body;
  const BOARD=cleanBoard((boardRoot&&boardRoot.getAttribute('data-board'))||(form&&form.getAttribute('data-board'))||'')||boardFromPath();
  const BOARD_LABEL=BOARD_LABELS[BOARD]||'Signal Board';
  const FEED_ROUTE=FEED_ROUTES[BOARD]||FEED_ROUTES.main;
  const SUBMIT_ROUTE=SUBMIT_ROUTES[BOARD]||SUBMIT_ROUTES.main;
  const REPORT_ROUTE=REPORT_ROUTES[BOARD]||REPORT_ROUTES.main;

  function esc(value){return String(value||'').replace(/[&<>"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[char]))}
  function when(value){try{return new Date(value).toLocaleString(undefined,{year:'numeric',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'})}catch{return''}}
  async function parse(response){const raw=await response.text();try{return JSON.parse(raw)}catch{return{error:raw||('HTTP '+response.status)}}}
  function listFrom(data){return Array.isArray(data)?data:(data&&Array.isArray(data.posts)?data.posts:[])}
  function loginUrl(){return'/member-login.html?return='+encodeURIComponent(location.pathname+location.hash)}
  function systemErrorLabel(prefix,error){const detail=error&&error.message?error.message:String(error||'request failed');return prefix+': '+detail}

  function isPublicUserPost(post){if(!post||typeof post!=='object')return false;const postStatus=String(post.status||'live').toLowerCase();if(['hidden','test','synthetic','draft','deleted','reported','spam','qa','check'].includes(postStatus))return false;const haystack=[post.id,post.title,post.body,post.message,post.category,post.name,post.sourceUrl].map(value=>String(value||'').toLowerCase()).join(' ');const syntheticMarkers=['synthetic check post','synthetic forum check','forum persistence check','automated forum check','automation check post','qa check post','pressure test post','site pressure test','test post from audit','github actions forum','build check post','health check post','demo post','seed post'];return!syntheticMarkers.some(marker=>haystack.includes(marker))}
  function lockFormToBoard(){if(!form)return;form.setAttribute('data-board',BOARD);let hidden=form.querySelector('input[name="board"]');if(!hidden){hidden=document.createElement('input');hidden.type='hidden';hidden.name='board';form.prepend(hidden)}hidden.value=BOARD}
  function applyAccess(){lockFormToBoard();const allowed=state.authenticated&&!state.checking;if(submitSection)submitSection.classList.toggle('signal-locked',!allowed);if(form)Array.from(form.elements).forEach(element=>{if(element.name!=='website')element.disabled=!allowed});const lockMessage=document.querySelector('.signal-lock-message');if(lockMessage)lockMessage.innerHTML=allowed?'Verified Free Member session active. Posts save to Cloudflare D1 and remain available across devices.':'A verified Free Member account is required to post. <a href="'+esc(loginUrl())+'">Log in or create a free account</a>.';if(accessStatus)accessStatus.textContent=state.checking?'Checking verified member session…':allowed?'Verified member session active. Persistent posting is open for '+BOARD_LABEL+'.':'Reading is open. Log in with a verified free account to post persistently.';if(accessButton){accessButton.textContent=allowed?'Verified Member — Posting Enabled':'Log in to post';accessButton.disabled=state.checking;accessButton.onclick=function(){if(allowed&&submitSection)submitSection.scrollIntoView({behavior:'smooth',block:'start'});else location.href=loginUrl()}}}
  function postBelongsHere(post){return String(post&&post.board||'main')===BOARD}
  function renderPost(post){const source=post.sourceUrl?'<p class="source-list"><a href="'+esc(post.sourceUrl)+'" target="_blank" rel="noopener">Open source</a></p>':'';const board=post.board?' <span class="pill">'+esc(BOARD_LABELS[post.board]||post.board)+'</span>':'';const verified=post.authorVerified?' <span class="pill">verified member</span>':'';return'<article class="card news-item"><span class="label">'+esc(post.category||'Signal')+'</span><h3>'+esc(post.title||'Signal')+'</h3><p>'+esc(post.body||post.message||'')+'</p>'+source+'<p><span class="pill">'+esc(post.name||'Verified Member')+'</span> <span class="pill">'+esc(when(post.approvedAt||post.createdAt||post.timestamp))+'</span>'+board+verified+' <span class="pill">persistent D1</span></p><button class="btn alt report-signal" type="button" data-id="'+esc(post.id)+'">Report post</button></article>'}
  function offlineNotice(message){return'<article class="card redline"><span class="label">Persistent Signal Board</span><h3>'+esc(BOARD_LABEL)+' cannot save right now</h3><p>No browser-only or temporary fallback is accepted. This board reads and writes only through Cloudflare D1.</p><p><strong>Detail:</strong> '+esc(message||'feed unavailable')+'</p><p><a class="btn alt" href="/forum-health">Check forum health</a></p></article>'}

  async function loadMember(){state.checking=true;applyAccess();try{const response=await fetch('/api/member/me',{cache:'no-store',headers:{accept:'application/json'}});const data=await parse(response);state.authenticated=Boolean(response.ok&&data.ok&&data.authenticated&&data.member&&data.member.emailVerifiedAt);state.member=state.authenticated?data.member:null}catch{state.authenticated=false;state.member=null}finally{state.checking=false;applyAccess()}}
  async function loadFeed(){if(!feed)return;lockFormToBoard();feed.innerHTML='<article class="card"><span class="label">persistent sync</span><h3>Signal Board is syncing</h3><p>Checking the authoritative Cloudflare D1 feed for '+esc(BOARD_LABEL)+'.</p></article>';try{const response=await fetch(FEED_ROUTE+'?t='+Date.now(),{cache:'no-store',headers:{accept:'application/json'}});const data=await parse(response);if(!response.ok||data.ok===false||data.persistent!==true)throw new Error(data.error||'persistent feed unavailable');const posts=listFrom(data).filter(postBelongsHere).filter(isPublicUserPost);feed.innerHTML=posts.length?posts.map(renderPost).join(''):'<article class="card redline"><h3>No persistent signals yet</h3><p>'+esc(BOARD_LABEL)+' is connected. Verified Free Members can post a source, question, reader note or public-record lead.</p></article>'}catch(error){feed.innerHTML=offlineNotice(systemErrorLabel('Feed failed',error))}}
  async function postLive(payload){const response=await fetch(SUBMIT_ROUTE,{method:'POST',cache:'no-store',headers:{'content-type':'application/json',accept:'application/json'},body:JSON.stringify(payload)});const data=await parse(response);if(response.status===401){state.authenticated=false;applyAccess();throw new Error(data.error||'Verified member login required')}if(!response.ok||data.ok===false||data.persistent!==true||!data.post||!data.post.id)throw new Error(data.error||('persistent post failed HTTP '+response.status));return data.post}
  async function reportPost(id){if(!state.authenticated){location.href=loginUrl();return}const reason=prompt('Report reason:');if(!reason)return;try{const response=await fetch(REPORT_ROUTE,{method:'POST',cache:'no-store',headers:{'content-type':'application/json',accept:'application/json'},body:JSON.stringify({id,board:BOARD,reason})});const data=await parse(response);if(!response.ok||data.ok===false)throw new Error(data.error||'persistent report failed');alert('Report saved persistently.')}catch(error){alert(systemErrorLabel('Report not saved',error))}}

  if(feed)feed.addEventListener('click',event=>{const button=event.target.closest('.report-signal');if(button)reportPost(button.getAttribute('data-id'))});
  if(form)form.addEventListener('submit',async event=>{event.preventDefault();lockFormToBoard();if(!state.authenticated){if(status)status.innerHTML='A verified Free Member account is required. <a href="'+esc(loginUrl())+'">Log in or create an account</a>.';return}const payload=Object.fromEntries(new FormData(form).entries());payload.board=BOARD;if(payload.website){status.textContent='Spam trap triggered.';return}status.textContent='Saving persistent post to '+BOARD_LABEL+'…';try{const livePost=await postLive(payload);form.reset();lockFormToBoard();status.textContent='Signal posted and stored persistently in Cloudflare D1.';if(feed&&isPublicUserPost(livePost))feed.innerHTML=renderPost(livePost)+(feed.innerHTML||'');await loadFeed();applyAccess()}catch(error){status.textContent=systemErrorLabel('Post not saved persistently',error);if(feed)feed.innerHTML=offlineNotice(status.textContent)+(feed.innerHTML||'');applyAccess()}});

  lockFormToBoard();applyAccess();Promise.all([loadMember(),loadFeed()]);
})();
