const statusNode=document.querySelector('#report-status');
const workspace=document.querySelector('#report-workspace');
const listNode=document.querySelector('#report-list');
const detailNode=document.querySelector('#report-detail');
const form=document.querySelector('#report-profile-form');
const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const date=value=>value?new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)):'Date unavailable';
async function requestJson(url,options={}){const response=await fetch(url,{credentials:'same-origin',headers:{accept:'application/json',...(options.body?{'content-type':'application/json'}:{})},...options});let data={};try{data=await response.json()}catch{}if(response.status===401){location.href=`/member-login.html?next=${encodeURIComponent(location.pathname+location.search)}`;throw new Error('Authentication required')}if(!response.ok)throw new Error(data.error||data.message||`Request failed (${response.status})`);return data}
function recordMarkup(record){const source=record.sourceName||record.sourceAsset||'Indexed source',recordDate=record.eventDate||record.publishedDate||record.updatedDate,link=record.route?`<p><a href="${escapeHtml(record.route)}">Open underlying record</a></p>`:'';return `<div class="record-card"><p><span class="badge">${escapeHtml(record.evidenceStatus||'REPORTED')}</span> <span class="badge">Source ${escapeHtml(record.sourceQuality||'D')}</span></p><h3>${escapeHtml(record.title)}</h3><p>${escapeHtml(record.summary||'Open the source record for the full context.')}</p><p class="report-meta">${escapeHtml(source)} · ${escapeHtml(date(recordDate))}</p>${link}</div>`}
function listMarkup(items,empty){return items?.length?`<ul>${items.map(item=>`<li>${escapeHtml(typeof item==='string'?item:item.title||item.summary||'')}</li>`).join('')}</ul>`:`<p class="report-meta">${escapeHtml(empty)}</p>`}
function renderReport(report){const sections=(report.trackerSections||[]).map(section=>`<section class="report-section"><h2>${escapeHtml(section.label)}</h2><p>${Number(section.currentCount||0)} current-period records; ${Number(section.totalMatched||0)} relevant indexed records reviewed.</p>${(section.records||[]).map(recordMarkup).join('')||'<p class="report-meta">No threshold-crossing record was found.</p>'}</section>`).join('');detailNode.innerHTML=`<p class="report-kicker">${escapeHtml(report.reportType||'Intelligence report')} · Version ${Number(report.version||1)}</p><h1>${escapeHtml(report.title||'Intelligence report')}</h1><p class="report-meta">Generated ${escapeHtml(date(report.generatedAt))} · Collection cutoff ${escapeHtml(date(report.sourceCollectionCutoff))}</p><div class="report-actions"><a class="report-action" href="/api/member/intelligence-reports/${encodeURIComponent(report.reportId)}/pdf">Download PDF dossier</a></div><section class="report-section"><h2>Executive overview</h2>${(report.executiveOverview||[]).map(item=>`<div class="record-card"><h3>${escapeHtml(item.subject)}</h3><p>${escapeHtml(item.assessment)}</p></div>`).join('')||'<p>No overview is available.</p>'}</section><section class="report-section"><h2>What changed since the previous report</h2>${listMarkup(report.whatChanged,'No material change was identified.')}</section>${sections}<section class="report-section"><h2>Connections discovered</h2>${(report.connections||[]).map(recordMarkup).join('')||'<p class="report-meta">No new material connection met the report threshold.</p>'}</section><section class="report-section"><h2>Contradictions and corrections</h2>${(report.contradictions||[]).map(recordMarkup).join('')||'<p class="report-meta">No contradiction or correction was identified.</p>'}</section><section class="report-section"><h2>What to watch</h2>${listMarkup(report.watchNext,'Continue monitoring primary records and corrections.')}</section><section class="report-section"><h2>Coverage limitations</h2>${listMarkup(report.coverageLimitations,'No limitation was recorded.')}</section>`}
async function openReport(id){detailNode.innerHTML='<p>Loading report…</p>';const data=await requestJson(`/api/member/intelligence-reports/${encodeURIComponent(id)}`);document.querySelectorAll('.report-button').forEach(button=>button.setAttribute('aria-current',String(button.dataset.id===id)));renderReport(data.report);history.replaceState({},'',`?report=${encodeURIComponent(id)}`)}
function renderList(reports){listNode.innerHTML=reports.length?reports.map(report=>`<button class="report-button" data-id="${escapeHtml(report.id)}"><strong>${escapeHtml(report.title)}</strong><br><span class="report-meta">v${Number(report.version)} · ${escapeHtml(date(report.generatedAt))} · ${Number(report.evidenceCount)} records</span></button>`).join(''):'<p>No personal report has been generated yet. Your first selected daily brief will create one.</p>';listNode.querySelectorAll('button').forEach(button=>button.addEventListener('click',()=>openReport(button.dataset.id).catch(showError)))}
function setProfile(profile){document.querySelector('#profile-depth').value=profile.depth||'essential';document.querySelector('#profile-history').checked=Boolean(profile.includeHistory);document.querySelector('#profile-speculation').checked=Boolean(profile.includeSpeculation);document.querySelector('#profile-sources').checked=Boolean(profile.includeRawSources);document.querySelector('#profile-delivery').value=profile.deliveryMode||'email_and_pdf';document.querySelector('#profile-alert').value=profile.alertThreshold||'major'}
function showError(error){statusNode.hidden=false;statusNode.textContent=error.message||String(error)}
form.addEventListener('submit',async event=>{event.preventDefault();statusNode.hidden=false;statusNode.textContent='Saving report settings…';try{const data=await requestJson('/api/member/report-profile',{method:'POST',body:JSON.stringify({depth:document.querySelector('#profile-depth').value,includeHistory:document.querySelector('#profile-history').checked,includeSpeculation:document.querySelector('#profile-speculation').checked,includeRawSources:document.querySelector('#profile-sources').checked,deliveryMode:document.querySelector('#profile-delivery').value,alertThreshold:document.querySelector('#profile-alert').value})});setProfile(data.profile);statusNode.textContent='Report settings saved.'}catch(error){showError(error)}});
try{const[reportsData,profileData]=await Promise.all([requestJson('/api/member/intelligence-reports?limit=50'),requestJson('/api/member/report-profile')]);renderList(reportsData.reports||[]);setProfile(profileData.profile||{});workspace.hidden=false;statusNode.hidden=true;const requested=new URL(location.href).searchParams.get('report'),initial=(reportsData.reports||[]).find(report=>report.id===requested)?.id||(reportsData.reports||[])[0]?.id;if(initial)await openReport(initial)}catch(error){showError(error)}
