(function(){
  function context(form){return [document.title,location.pathname,form.getAttribute('name'),form.id,form.className,form.textContent].join(' ').toLowerCase()}
  function emailInput(form){return form.querySelector('input[type="email"],input[name="email"],input[name="Email"]')}
  function status(form){let s=form.querySelector('.form-status,.newsletter-status,[data-newsletter-status]');if(!s){s=document.createElement('p');s.className='form-status newsletter-status';form.appendChild(s)}return s}
  function shouldCapture(form){const email=emailInput(form);if(!email)return false;const hay=context(form);return /newsletter|black file|opt.?in|lead magnet|weekly|digest|brief|request|get the file|download|signal path/.test(hay)}
  function consentInput(form){return form.querySelector('input[name="marketingConsent"],input[name="consent"]')}
  function ensureConsent(form){let input=consentInput(form);if(input)return input;const label=document.createElement('label');label.className='warning membership-consent';input=document.createElement('input');input.type='checkbox';input.name='marketingConsent';input.value='yes';input.required=true;label.appendChild(input);label.appendChild(document.createTextNode(' I agree to receive Matrix Reprogrammed email updates and understand I can unsubscribe at any time.'));const button=form.querySelector('button[type="submit"],input[type="submit"]');if(button)form.insertBefore(label,button);else form.appendChild(label);return input}
  async function submit(form,event){event.preventDefault();const email=emailInput(form);const consent=ensureConsent(form);const s=status(form);const body={email:email.value,name:(form.querySelector('[name="name"],[name="Name"]')||{}).value||'',source:document.title,sourcePage:location.pathname,interest:context(form).slice(0,300),marketingConsent:Boolean(consent&&consent.checked),consentVersion:'membership-consent-v1'};if(!body.email||!/@/.test(body.email)){s.textContent='Enter a valid email address.';return}if(!body.marketingConsent){s.textContent='Please confirm that you agree to receive email updates.';return}s.textContent='Joining the Weekly Signal…';try{const res=await fetch('/api/membership/signup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await res.json();if(!res.ok||!data.ok)throw new Error(data.error||'Signup failed');s.textContent=data.emailSent?'Check your email for your verification link.':'You have joined the Weekly Signal.';if(data.downloadUrl)setTimeout(()=>{location.href=data.downloadUrl},500)}catch(err){s.textContent='We could not complete the signup. Please try again.'}}
  function boot(){document.querySelectorAll('form').forEach(form=>{if(!shouldCapture(form)||form.dataset.newsletterCapture==='active')return;ensureConsent(form);form.dataset.newsletterCapture='active';form.addEventListener('submit',submit.bind(null,form));});}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
