(function(){
const input=document.getElementById('archive-search'),results=document.getElementById('search-results'),count=document.getElementById('search-count'),answer=document.getElementById('ask-answer'),shortcuts=document.getElementById('ask-shortcuts');
if(!input||!results)return;
const stop=new Set('the,and,for,with,what,where,when,why,how,does,into,from,that,this,show,about,latest,update,updates,are,all,site,page,pages,tell,me'.split(','));
const layerMap={
'money-reserves':['gold','reserve','custody','vault','central','bank','money','payment','cbdc','wallet','debt'],
'identity-access':['identity','digital','access','wallet','login','agenda','2030','sdg','mandatory'],
'information-narrative':['brain','brief','narrative','media','censorship','search','source','document'],
'security-emergency':['security','emergency','surveillance','border','intelligence','cyber','war'],
'elite-networks':['elite','billionaire','foundation','institution','wef','blackrock','control','power'],
'disclosure-black-files':['epstein','disclosure','redaction','withheld','sealed','court','file','records'],
'speculation-review':['speculation','claim','frazzledrip','clinton','metadata','counter','source']};
function esc(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function words(q){return String(q||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').split(/\s+/).filter(w=>w.length>1&&!stop.has(w));}
function keys(i){return Array.isArray(i.keywords)?i.keywords:String(i.keywords||'').split(/[, ]+/).filter(Boolean);}
function hay(i){return [i.title,i.category,i.layer,i.description,keys(i).join(' ')].join(' ').toLowerCase();}
function queryLayer(tokens){let best=null;for(const [layer,terms] of Object.entries(layerMap)){const s=terms.reduce((n,t)=>n+(tokens.includes(t)?1:0),0);if(s&&(!best||s>best.score))best={layer,score:s};}return best;}
function score(i,tokens,q){const h=hay(i);let s=Number(i.priority||0)/4;if(!tokens.length)return s;for(const t of tokens){if(String(i.title||'').toLowerCase().includes(t))s+=22;if(String(i.category||'').toLowerCase().includes(t))s+=12;if(String(i.layer||'').toLowerCase().includes(t))s+=10;if(keys(i).join(' ').toLowerCase().includes(t))s+=14;if(h.includes(t))s+=4;}if(q&&h.includes(q.toLowerCase()))s+=30;const l=queryLayer(tokens);if(l&&String(i.layer||'')===l.layer)s+=24;return s;}
function card(i){const pills=[i.category,i.layer,i.sourceType].filter(Boolean).slice(0,3).map(x=>'<span class="pill">'+esc(x)+'</span>').join('');return '<article class="card redline"><span class="label">'+esc(i.category||'Route')+'</span><h3>'+esc(i.title)+'</h3><p>'+esc(i.description||'Open this route for deeper context.')+'</p><p>'+pills+'</p><div class="cta-row small"><a class="btn" href="'+esc(i.url)+'">Open Route</a><a class="btn alt" href="control-structure.html">Control Map</a><a class="btn alt" href="evidence-vault.html">Evidence</a></div></article>';}
function status(q, ranked, tokens){const top=ranked[0],l=queryLayer(tokens);if(!answer)return;if(!q)answer.textContent='SEARCH V2 STATUS\n> Brain-aware index: active\n> Type a question to rank the control structure\n> HTML + JSON feeds indexed\n> Mission routes boosted';else if(top)answer.textContent='SEARCH V2 ROUTE\n> Query: '+q+'\n> Layer: '+(l?l.layer:'general')+'\n> Best route: '+top.title+'\n> Open: '+top.url+'\n> Boundary: search routing is not proof. Follow the evidence route.';else answer.textContent='SEARCH V2 ROUTE\n> No direct match. Try control structure, gold custody, digital ID, Epstein redaction, billionaire watch, or speculation review.';}
function render(index,q=''){const tokens=words(q);let ranked=index.map(i=>({...i,_score:score(i,tokens,q)})).filter(i=>!q||i._score>Number(i.priority||0)/4).sort((a,b)=>b._score-a._score||String(a.title).localeCompare(String(b.title))).slice(0,q?36:24);count&&(count.textContent=(q?'Found ':'Showing ')+ranked.length+' route'+(ranked.length===1?'':'s'));results.innerHTML=ranked.length?ranked.map(card).join(''):'<article class="card redline"><h3>No direct route found</h3><p>Try control structure, gold custody, digital identity, Epstein redaction, billionaire watch, speculation, books, or evidence.</p></article>';status(q,ranked,tokens);}
function init(index){index=Array.isArray(index)?index:[];function run(){render(index,input.value.trim());}input.addEventListener('input',run);shortcuts&&shortcuts.addEventListener('click',e=>{const b=e.target.closest('button[data-q]');if(!b)return;input.value=b.dataset.q||'';run();input.focus();});run();}
fetch('/search-index.json',{cache:'no-store',headers:{Accept:'application/json'}}).then(r=>{if(!r.ok)throw new Error('HTTP '+r.status);return r.json();}).then(init).catch(err=>{count&&(count.textContent='Search index failed to load');results.innerHTML='<article class="card redline"><h3>Search fallback</h3><p>Open the Control Structure Map, Daily Brain Brief, Evidence Vault, or Books while the index refreshes.</p><div class="cta-row small"><a class="btn" href="control-structure.html">Control Map</a><a class="btn alt" href="daily-brain-brief.html">Daily Brief</a><a class="btn alt" href="evidence-vault.html">Evidence</a></div></article>';answer&&(answer.textContent='SEARCH V2 STATUS\n> Fallback active\n> '+String(err.message||err).slice(0,120));});
})();