(function(){
const input=document.getElementById("archive-search"),results=document.getElementById("search-results"),count=document.getElementById("search-count"),answer=document.getElementById("ask-answer"),shortcuts=document.getElementById("ask-shortcuts");
if(!input||!results)return;
const stop=new Set("the,and,for,with,what,where,when,why,how,does,into,from,that,this,show,about,latest,update,updates,are,all,site,page,pages,tell,me".split(","));
const layerMap={"money-reserves":["gold","reserve","custody","vault","central","bank","money","payment","cbdc","wallet","debt"],"identity-access":["identity","digital","access","wallet","login","agenda","2030","sdg","mandatory"],"information-narrative":["brain","brief","narrative","media","censorship","search","source","document"],"security-emergency":["security","emergency","surveillance","border","intelligence","cyber","war"],"elite-networks":["elite","billionaire","foundation","institution","wef","blackrock","control","power"],"disclosure-black-files":["epstein","disclosure","redaction","withheld","sealed","court","file","records"],"speculation-review":["speculation","claim","frazzledrip","clinton","metadata","counter","source"]};
function esc(s){return String(s||"").replace(/[&<>]/g,function(c){return c==="&"?"&amp;":c==="<"?"&lt;":"&gt;";});}
function words(q){return String(q||"").toLowerCase().replace(/[^a-z0-9]+/g," ").split(/\s+/).filter(function(w){return w.length>1&&!stop.has(w);});}
function keys(i){return Array.isArray(i.keywords)?i.keywords:String(i.keywords||"").split(/[, ]+/).filter(Boolean);}
function hay(i){return [i.title,i.category,i.layer,i.description,keys(i).join(" ")].join(" ").toLowerCase();}
function queryLayer(tokens){let best=null;for(const layer in layerMap){const terms=layerMap[layer];const s=terms.reduce(function(n,t){return n+(tokens.includes(t)?1:0);},0);if(s&&(!best||s>best.score))best={layer:layer,score:s};}return best;}
function score(i,tokens,q){const h=hay(i);let s=Number(i.priority||0)/4;if(!tokens.length)return s;for(const t of tokens){if(String(i.title||"").toLowerCase().includes(t))s+=22;if(String(i.category||"").toLowerCase().includes(t))s+=12;if(String(i.layer||"").toLowerCase().includes(t))s+=10;if(keys(i).join(" ").toLowerCase().includes(t))s+=14;if(h.includes(t))s+=4;}if(q&&h.includes(String(q).toLowerCase()))s+=30;const l=queryLayer(tokens);if(l&&String(i.layer||"")===l.layer)s+=24;return s;}
function card(i){const pills=[i.category,i.layer,i.sourceType].filter(Boolean).slice(0,3).map(function(x){return "<span class=\"pill\">"+esc(x)+"</span>";}).join("");return "<article class=\"card redline\"><span class=\"label\">"+esc(i.category||"Route")+"</span><h3>"+esc(i.title)+"</h3><p>"+esc(i.description||"Open this route for deeper context.")+"</p><p>"+pills+"</p><div class=\"cta-row small\"><a class=\"btn\" href=\""+esc(i.url)+"\">Open Route</a><a class=\"btn alt\" href=\"control-structure.html\">Control Map</a><a class=\"btn alt\" href=\"evidence-vault.html\">Evidence</a></div></article>";}
function status(q,ranked,tokens){const top=ranked[0],l=queryLayer(tokens);if(!answer)return;if(!q)answer.textContent=["SEARCH V2 STATUS","> Brain-aware index: active","> Type a question to rank the control structure","> HTML + JSON feeds indexed","> Mission routes boosted"].join("\n");else if(top)answer.textContent=["SEARCH V2 ROUTE","> Query: "+q,"> Layer: "+(l?l.layer:"general"),"> Best route: "+top.title,"> Open: "+top.url,"> Boundary: search routing is not proof. Follow the evidence route."].join("\n");else answer.textContent=["SEARCH V2 ROUTE","> No direct match. Try control structure, gold custody, digital ID, Epstein redaction, billionaire watch, or speculation review."].join("\n");}
function render(index,q){q=q||"";const tokens=words(q);let ranked=index.map(function(i){return Object.assign({},i,{_score:score(i,tokens,q)});}).filter(function(i){return !q||i._score>Number(i.priority||0)/4;}).sort(function(a,b){return b._score-a._score||String(a.title).localeCompare(String(b.title));}).slice(0,q?36:24);if(count)count.textContent=(q?"Found ":"Showing ")+ranked.length+" route"+(ranked.length===1?"":"s");results.innerHTML=ranked.length?ranked.map(card).join(""):"<article class=\"card redline\"><h3>No direct route found</h3><p>Try control structure, gold custody, digital identity, Epstein redaction, billionaire watch, speculation, books, or evidence.</p></article>";status(q,ranked,tokens);}
function init(index){index=Array.isArray(index)?index:[];function run(){render(index,input.value.trim());}input.addEventListener("input",run);if(shortcuts)shortcuts.addEventListener("click",function(e){const b=e.target.closest("button[data-q]");if(!b)return;input.value=b.dataset.q||"";run();input.focus();});run();}
const fallbackIndex=[{"title":"Control Structure Map","url":"control-structure.html","category":"Main Mission","layer":"control-structure","description":"Open the seven-layer control map.","keywords":["control","power","structure"],"priority":100},{"title":"Daily Brain Brief","url":"daily-brain-brief.html","category":"Living Brain","layer":"information-narrative","description":"Open the latest conclusions and watch list.","keywords":["daily","brain","brief"],"priority":98},{"title":"Evidence Vault","url":"evidence-vault.html","category":"Evidence","layer":"disclosure-black-files","description":"Follow source documents and evidence routes.","keywords":["evidence","records","documents"],"priority":92},{"title":"Books","url":"books.html","category":"Books","layer":"general","description":"Open the Matrix Reprogrammed book archive.","keywords":["books","archive"],"priority":80}];
function loadSearchIndex(){
return fetch('/search-index.json',{cache:'no-store',headers:{Accept:'application/json'}}).then(async function(r){
const type=String(r.headers.get('content-type')||'').toLowerCase();
const text=await r.text();
if(!r.ok)throw new Error('HTTP '+r.status);
if(!type.includes('application/json')||/^\s*</.test(text))throw new Error('HTML returned instead of JSON');
let parsed;try{parsed=JSON.parse(text);}catch(e){throw new Error("Invalid search JSON: "+e.message);}
if(!Array.isArray(parsed))throw new Error('Search index is not an array');
return parsed;
});
}
loadSearchIndex().then(init).catch(function(err){
init(fallbackIndex);
if(count)count.textContent="Search index unavailable — showing verified fallback routes";
if(answer)answer.textContent=["SEARCH V2 STATUS","> Fallback index active","> "+String(err.message||err).slice(0,120),"> Verified mission routes remain available"].join("\n");
});
})();