const fs = require('fs');
const path = require('path');

const root = process.cwd();
const generatedAllowList = new Set(['downloads/the-black-file-matrix-reprogrammed.pdf']);
const ignoredDirs = new Set(['.git', 'node_modules']);
const publicHtmlFiles = [];
const allFiles = new Set();
function walk(dir) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (ignoredDirs.has(entry.name)) continue;
    const full = path.join(dir, entry.name);
    const rel = path.relative(root, full).replace(/\\/g, '/');
    if (entry.isDirectory()) walk(full);
    else { allFiles.add(rel); if (entry.name.endsWith('.html')) publicHtmlFiles.push(rel); }
  }
}
walk(root);
const bannedPublicPhrases = [/ChatGPT/i,/author[- ]facing/i,/placeholder/i,/pending functionality/i,/awaiting API/i,/next build stage/i,/future build/i,/I can later/i,/TODO/i,/FIXME/i,/mapping needed/i,/ASIN missing/i,/once deployed/i,/generated by/i,/setup guide/i,/send exact/i];
const publicExceptions = new Set(['funnel-map.html']);
function stripHashAndQuery(href){return href.split('#')[0].split('?')[0].trim();}
function isExternalOrProtocol(href){return /^(https?:|mailto:|tel:|javascript:|data:)/i.test(href)||href.startsWith('#')||href==='';}
function hasAnchor(html, anchor){if(!anchor)return true;const safe=anchor.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');return new RegExp(`\\sid=["']${safe}["']`,'i').test(html)||new RegExp(`\\sname=["']${safe}["']`,'i').test(html);}
const htmlCache = new Map();
function readHtml(file){if(!htmlCache.has(file))htmlCache.set(file,fs.readFileSync(path.join(root,file),'utf8'));return htmlCache.get(file);}
const problems=[];
for(const file of publicHtmlFiles){const html=readHtml(file);const isInternalPage=publicExceptions.has(file)||/<meta\s+name=["']robots["']\s+content=["'][^"']*noindex/i.test(html);if(!isInternalPage){for(const phrase of bannedPublicPhrases){if(phrase.test(html))problems.push(`${file}: public-facing copy contains banned build-note phrase: ${phrase}`);}}const attrRegex=/(?:href|src)=["']([^"']+)["']/gi;let match;while((match=attrRegex.exec(html))!==null){const raw=match[1].trim();if(isExternalOrProtocol(raw))continue;const [targetPart,anchor]=raw.split('#');const target=stripHashAndQuery(targetPart);if(!target)continue;const resolved=path.normalize(path.join(path.dirname(file),target)).replace(/\\/g,'/');if(resolved.startsWith('..')){problems.push(`${file}: link escapes site root: ${raw}`);continue;}if(!allFiles.has(resolved)&&!generatedAllowList.has(resolved)){problems.push(`${file}: missing internal link/asset target: ${raw} -> ${resolved}`);continue;}if(anchor&&resolved.endsWith('.html')){const targetHtml=readHtml(resolved);if(!hasAnchor(targetHtml,anchor))problems.push(`${file}: missing anchor target: ${raw}`);}}}
const requiredCoreFiles=['index.html','styles.css','matrix.js','books.html','black-file.html','news.html','intel-archive.html','timers.html','epstein-files.html','black-file-index.html','answer-index.html','sitemap.xml','robots.txt','llms.txt','netlify.toml','data/bulletins.json','data/human-cost.json'];
for(const required of requiredCoreFiles){if(!allFiles.has(required))problems.push(`missing required core file: ${required}`);}
if(allFiles.has('data/bulletins.json')){const bulletins=JSON.parse(fs.readFileSync(path.join(root,'data/bulletins.json'),'utf8'));if(!Array.isArray(bulletins.bulletins)||bulletins.bulletins.length<3)problems.push('data/bulletins.json: expected at least 3 bulletins');for(const b of bulletins.bulletins||[]){for(const field of ['id','date','label','headline','summary','why','path']){if(!b[field])problems.push(`data/bulletins.json: bulletin missing ${field}`);}if(!Array.isArray(b.sources)||!b.sources.length)problems.push(`data/bulletins.json: ${b.id||b.headline} missing sources`);}}
if(allFiles.has('data/human-cost.json')){const hc=JSON.parse(fs.readFileSync(path.join(root,'data/human-cost.json'),'utf8'));if(!Array.isArray(hc.panels)||hc.panels.length<6)problems.push('data/human-cost.json: expected at least 6 human-cost panels');for(const p of hc.panels||[]){for(const field of ['key','title','figure','status','description','sourceLabel']){if(!p[field])problems.push(`data/human-cost.json: panel ${p.key||p.title||'unknown'} missing ${field}`);}}}
if(allFiles.has('news.html')){const news=readHtml('news.html');const newsItemCount=(news.match(/class=["'][^"']*news-item/g)||[]).length;const metricCount=(news.match(/class=["'][^"']*metric/g)||[]).length;if(!/Latest 7 Days/i.test(news))problems.push('news.html: missing visible Latest 7 Days heading');if(newsItemCount<3)problems.push(`news.html: expected at least 3 visible news bulletin cards, found ${newsItemCount}`);if(metricCount<10)problems.push(`news.html: expected at least 10 visible metric panels, found ${metricCount}`);if(!/Human Cost/i.test(news))problems.push('news.html: missing Human Cost panel');if(!/Migration \/ Irregular Immigration/i.test(news))problems.push('news.html: missing Migration / Irregular Immigration panel');if(!/Vaccines/i.test(news))problems.push('news.html: missing Vaccines panel');}
if(allFiles.has('intel-archive.html')){const archive=readHtml('intel-archive.html');const archiveCards=(archive.match(/<article class=["']card/g)||[]).length;if(!/BULLETIN ARCHIVE/i.test(archive))problems.push('intel-archive.html: missing Bulletin Archive heading');if(archiveCards<3)problems.push(`intel-archive.html: expected at least 3 archived bulletin cards, found ${archiveCards}`);}
if(problems.length){console.error('\nSITE QA FAILED\n');for(const problem of problems)console.error(`- ${problem}`);console.error(`\n${problems.length} issue(s) found.\n`);process.exit(1);}console.log(`SITE QA PASSED: ${publicHtmlFiles.length} HTML files checked.`);console.log('Internal links/assets passed. Intel Desk, archive, Human Cost panels, migration panel, sitemap, llms, and data files passed.');
