const fs = require('fs');
const path = require('path');

const root = process.cwd();
const generatedAllowList = new Set([
  'downloads/the-black-file-matrix-reprogrammed.pdf'
]);

const ignoredDirs = new Set(['.git', 'node_modules']);
const publicHtmlFiles = [];
const allFiles = new Set();

function walk(dir) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (ignoredDirs.has(entry.name)) continue;
    const full = path.join(dir, entry.name);
    const rel = path.relative(root, full).replace(/\\/g, '/');
    if (entry.isDirectory()) walk(full);
    else {
      allFiles.add(rel);
      if (entry.name.endsWith('.html')) publicHtmlFiles.push(rel);
    }
  }
}

walk(root);

const bannedPublicPhrases = [
  /ChatGPT/i,
  /author[- ]facing/i,
  /placeholder/i,
  /lead[- ]magnet/i,
  /pending functionality/i,
  /pending product/i,
  /awaiting API/i,
  /next build stage/i,
  /NEXT SITE STEP/i,
  /future build/i,
  /I can later/i,
  /your screenshot/i,
  /screenshots/i,
  /user[- ]provided/i,
  /mapping needed/i,
  /exact ASIN/i,
  /ASIN missing/i,
  /direct product buttons appear only/i,
  /Form capture activates/i,
  /once deployed/i,
  /Netlify Forms/i,
  /KDP data extracted/i,
  /generated by/i,
  /TODO/i,
  /FIXME/i,
  /Internal Funnel Map/i,
  /setup guide/i,
  /build status/i,
  /author central/i,
  /send exact/i
];

const publicExceptions = new Set([
  'funnel-map.html'
]);

function stripHashAndQuery(href) {
  return href.split('#')[0].split('?')[0].trim();
}

function isExternalOrProtocol(href) {
  return /^(https?:|mailto:|tel:|javascript:|data:)/i.test(href) || href.startsWith('#') || href === '';
}

function hasAnchor(html, anchor) {
  if (!anchor) return true;
  const safe = anchor.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  return new RegExp(`\\sid=["']${safe}["']`, 'i').test(html) || new RegExp(`\\sname=["']${safe}["']`, 'i').test(html);
}

const htmlCache = new Map();
function readHtml(file) {
  if (!htmlCache.has(file)) htmlCache.set(file, fs.readFileSync(path.join(root, file), 'utf8'));
  return htmlCache.get(file);
}

const problems = [];

for (const file of publicHtmlFiles) {
  const html = readHtml(file);
  const isInternalPage = publicExceptions.has(file) || /<meta\s+name=["']robots["']\s+content=["'][^"']*noindex/i.test(html);

  if (!isInternalPage) {
    for (const phrase of bannedPublicPhrases) {
      if (phrase.test(html)) problems.push(`${file}: public-facing copy contains banned build-note phrase: ${phrase}`);
    }
  }

  const attrRegex = /(?:href|src)=["']([^"']+)["']/gi;
  let match;
  while ((match = attrRegex.exec(html)) !== null) {
    const raw = match[1].trim();
    if (isExternalOrProtocol(raw)) continue;
    const [targetPart, anchor] = raw.split('#');
    const target = stripHashAndQuery(targetPart);
    if (!target) continue;
    const resolved = path.normalize(path.join(path.dirname(file), target)).replace(/\\/g, '/');
    if (resolved.startsWith('..')) {
      problems.push(`${file}: link escapes site root: ${raw}`);
      continue;
    }
    if (!allFiles.has(resolved) && !generatedAllowList.has(resolved)) {
      problems.push(`${file}: missing internal link/asset target: ${raw} -> ${resolved}`);
      continue;
    }
    if (anchor && resolved.endsWith('.html')) {
      const targetHtml = readHtml(resolved);
      if (!hasAnchor(targetHtml, anchor)) problems.push(`${file}: missing anchor target: ${raw}`);
    }
  }
}

const requiredCoreFiles = [
  'index.html',
  'styles.css',
  'matrix.js',
  'welcome-gate.css',
  'welcome-gate.js',
  'books.html',
  'black-file.html',
  'news.html',
  'videos.html',
  'sitemap.xml',
  'robots.txt',
  'netlify.toml'
];

for (const required of requiredCoreFiles) {
  if (!allFiles.has(required)) problems.push(`missing required core file: ${required}`);
}

if (allFiles.has('news.html')) {
  const news = readHtml('news.html');
  const newsItemCount = (news.match(/class=["'][^"']*news-item/g) || []).length;
  if (!/Latest 7 Days/i.test(news)) problems.push('news.html: missing visible Latest 7 Days heading');
  if (newsItemCount < 3) problems.push(`news.html: expected at least 3 visible news bulletin cards, found ${newsItemCount}`);
  if (/desk is ready|short-bulletin desk is active|Candidate list updates after/i.test(news)) problems.push('news.html: contains placeholder news desk copy');
  if (!/Human Cost/i.test(news)) problems.push('news.html: missing Human Cost panel');
}

if (problems.length) {
  console.error('\nSITE QA FAILED\n');
  for (const problem of problems) console.error(`- ${problem}`);
  console.error(`\n${problems.length} issue(s) found.\n`);
  process.exit(1);
}

console.log(`SITE QA PASSED: ${publicHtmlFiles.length} HTML files checked.`);
console.log('Internal links/assets passed. Public pages passed banned build-note scan. News and Human Cost panel passed.');
